### ISSUE TITLE
Base implementaton on CPU

### ISSUE THREAD

**Issue by nViso** [gplhegde/caffepresso#1]
Have you considered making a simple dependency free CPU implementation?

It would be useful to check from the code generation tools if other networks can be bench-marked, however for this having a simple CPU only implementation would be useful.

**Comment by gplhegde** [comment]
e switch to get rid of all dependencies.
When you are targeting CPU, take a note that the CPU version code is not optimized. I wrote it to generate a reference output for comparison. I didn't even use standard libraries such as BLAS because some of the platforms that we used do not have a port for these libraries. Also, the implementation was targetted to bare-metal applications. You may want to use these libraries to get better performance on CPU ( like using NEON intrinsics). 
I am sorry that the repo is not well documented. Let me know if you get stuck in between.
If you are starting on this, https://github.com/gplhegde/caffepresso/blob/master/mxp and https://github.com/gplhegde/caffepresso/blob/master/dsp are in better shape than any other platform-specific directories.
